version: '3.3'
services:
    web:
        build: .
        ports:
            - '4000:4000'
        command: mix phx.server
        environment:
            - MIX_ENV=dev
            - PORT=4000
        volumes:
            - .:/app

    db:
        image: mysql:5.7
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: phx_test_satabase
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4
                --collation-server=utf8mb4_unicode_ci

        volumes:
        - ./docker/db/data:/var/lib/mysql
        - ./docker/db/my.cnf:/etc/mysql/conf.d/my.conf
        - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
        - 3306:3306
